server:
  port: 8010
spring:
  application:
    name: consumer-movie
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
#自定义负载均衡策略
provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.neflix.loadbalancer.RandomRule
