spring:
  application:
    name: discovery-eureka-ha
security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  client:
    service-url:
      #将自己注册到peer2
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: peer1
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      #将自己注册到peer1
      defaultZone: http://localhost:8761/eureka/