server:
  port: 8010
spring:
  application:
    name: consumer-movie
provider-user:
  ribbon:
    listOfServers: localhost:8000,localhost:8001
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule